
services:
  db:
    image: postgres:16.3
    container_name: postgres-db
    environment:
      POSTGRES_DB: social_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpassword
    volumes:
      - data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

volumes:
  data:
